### ISSUE TITLE
README claims compatibility with python 3.8+, but TypeAlias was added in python 3.10

### ISSUE THREAD

**Issue by phantom-jacob** [lljbash/clangd-tidy#3]
https://github.com/lljbash/clangd-tidy/blob/4cbc11f85a2b07317181709f9c1cae6da60c683b/diagnostic_formatter.py#L4

**Comment by lljbash** [comment]
Thanks for catching that!

You're right, TypeAlias is a Python 3.10 feature. I'll update the code to work with Python 3.8. Fix coming soon!
