### ISSUE TITLE
Publish to pypi?

### ISSUE THREAD

**Issue by itavero** [lljbash/clangd-tidy#4]
Do you plan to publish this to the Python Package Index?
Would be nice if it can easily be installed via something like `pip`.

**Comment by lljbash** [comment]
I'm glad to know that this project is actually helpful.

I was planning to publish this once some people have actually started using it. Maybe now is the time. :smiley:

**Comment by lljbash** [comment]
[clangd-tidy](https://pypi.org/project/clangd-tidy/) has been published on PyPI. 🎉

Just `pip install clangd-tidy`.
